### ISSUE TITLE
Error Converting weights of p7 from pytorch to tensorflow. Could you help in this

### ISSUE THREAD

**Issue by Palak-15** [wangermeng2021/ScaledYOLOv4-tensorflow2#16]
I have tried converted .pt model to .onxx and then onxx to pb file for tensorflow. I have checked the graph using neutron => 1 transpose layer has been added so that it can handle NHWC input of tensorflow.

**Comment by Palak-15** [comment]
Solved!

**Comment by tylertroy** [comment]
@Palak-15 How did you solve this?
